### SERVER COMMANDER CONFIGURATION - SERVER
###
###

### NETWORKING
bind_ip=0.0.0.0
bind_port=8080

### METRICS
# You can configure here how the server handles the metrics, which are collected and arent, and loads more. This all
# depends on what you want to store in the database, and how much system resource you are okay with being used by the
# program.
metric_logging_interval=15

### Database Connection
# The server can only handle local SQLite databases. However, for your own purposes you can store this somewhere
# differently. Unless explicitly stated, the file will be stored with the server files.
database_path=database.db

